#pragma once
#include <map>
#include <string>

const std::map<std::string, int> cTagMap = {
        { "<base>", 1 },
        { "<style>", 2 },
        { "<script>", 3 },
        { "<body>", 4 },
        { "<article>", 5 },
        { "<section>", 6 },
        { "<nav>", 7 },
        { "<aside>", 8 },
        { "<h1>", 9 },
        { "<h2>", 10 },
        { "<h3>", 11 },
        { "<h4>", 12 },
        { "<h5>", 13 },
        { "<h6>", 14 },
        { "<header>", 15 },
        { "<footer>", 16 },
        { "<address>", 17 },
        { "<main>", 18 },
        { "<p>", 19 },
        { "<hr>", 20 },
        { "<pre>", 21 },
        { "<blockquote>", 22 },
        { "<ol>", 23 },
        { "<ul>", 24 },
        { "<li>", 25 },
        { "<dl>", 26 },
        { "<dt>", 27 },
        { "<dd>", 28 },
        { "<figure>", 29 },
        { "<figcaption>", 30 },
        { "<div>", 31 },
        { "<a>", 32 },
        { "<em>", 33 },
        { "<strong>", 34 },
        { "<small>", 35 },
        { "<s>", 36 },
        { "<cite>", 37 },
        { "<q>", 38 },
        { "<dfn>", 39 },
        { "<abbr>", 40 },
        { "<time>", 41 },
        { "<code>", 42 },
        { "<var>", 43 },
        { "<samp>", 44 },
        { "<kbd>", 45 },
        { "<sub>", 46 },
        { "<sup>", 47 },
        { "<i>", 48 },
        { "<b>", 49 },
        { "<mark>", 50 },
        { "<ruby>", 51 },
        { "<rt>", 52 },
        { "<rp>", 53 },
        { "<bdi>", 54 },
        { "<bdo>", 55 },
        { "<span>", 56 },
        { "<br>", 57 },
        { "<wbr>", 58 },
        { "<ins>", 59 },
        { "<del>", 60 },
        { "<img>", 61 },
        { "<iframe>", 62 },
        { "<embed>", 63 },
        { "<object>", 64 },
        { "<param>", 65 },
        { "<video>", 66 },
        { "<audio>", 67 },
        { "<source>", 68 },
        { "<track>", 69 },
        { "<map>", 70 },
        { "<area>", 71 },
        { "<table>", 72 },
        { "<caption>", 73 },
        { "<colgroup>", 74 },
        { "<col>", 75 },
        { "<tbody>", 76 },
        { "<thead>", 77 },
        { "<tfoot>", 78 },
        { "<tr>", 79 },
        { "<td>", 80 },
        { "<th>", 81 },
        { "<form>", 82 },
        { "<fieldset>", 83 },
        { "<legend>", 84 },
        { "<label>", 85 },
        { "<input>", 86 },
        { "<button>", 87 },
        { "<select>", 88 },
        { "<optgroup>", 89 },
        { "<option>", 90 },
        { "<textarea>", 91 },
        { "<output>", 92 },
        { "<progress>", 93 },
        { "<meter>", 94 },
        { "<details>", 95 },
        { "<summary>", 96 },
        { "<menu>", 97 },
        { "<menuitem>", 98 },
        { "<dialog>", 99 },
        { "<noscript>", 100}
    };

const std::map<std::string, int> cTagCloseMap = {
    {"<br>", 120},
    {"<hr>", 121},
    {"<img>", 122},
    {"<input>", 123},
    {"<link>", 124},
    {"<meta>", 125},
    {"<area>", 126},
    {"<base>", 127},
    {"<col>", 128},
    {"<command>", 129},
    {"<embed>", 130},
    {"<keygen>", 131},
    {"<param>", 132},
    {"<source>", 133},
    {"<track>", 134},
    {"<wbr>", 135}
    };